packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json

flow-icons peer dependecies updated

---

packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

- `f-md-editor` peerDependencies updated.

md-editor peer dependecies updated

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-icon-button/f-icon-button.ts
packages/flow-core/src/components/f-icon/f-icon.ts

- default `aria-label` application removed

Aria label bug fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-select/render.ts

- `lit-virtualizer` registration bug fixed.

lit-virtualizer-bug fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-select/render.ts
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

Lit virtualizer bug

---

packages/flow-core-config/CHANGELOG.md
packages/flow-core-config/package.json
packages/flow-core-config/src/index.ts

- setting custom font api typo fixed.

NFX-255-2 setting font typo fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-text-area/f-text-area.scss
packages/flow-core/src/components/f-text-area/f-text-area.test.ts
packages/flow-core/src/components/f-text-area/f-text-area.ts
stories/flow-core/f-text-area.stories.js
stories/flow-core/f-text-area.stories.ts

- `f-textarea` auto height if `rows` are not specified.

NFX-262 `f-textarea` auto height if `rows` are not specified.

---

packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

- bump version to use latest flow-cor

NFX-281-2 version bump to fix multiple flow getting installed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-counter/f-counter.ts
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

- `f-counter` part added to customize inner css

NFX-281 part added in f-counter

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-button/f-button.ts
stories/flow-core/f-button.stories.ts

- `f-button` click event and action event issue fixed.

NFX-374 f-button click and action event issue fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-accordion/f-accordion.ts

- `f-accordion` scroll isssue fixed

NFX-391-3 accordion scroll issue fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-select/handlers.ts
packages/flow-core/src/components/f-select/render.ts

- `f-select` auto-complete removed from search input
- `f-select` group search issue fixed.

NFX-405 f-select autocomplete issue fixed

---

packages/flow-code-editor/CHANGELOG.md
packages/flow-code-editor/package.json
packages/flow-core-config/CHANGELOG.md
packages/flow-core-config/package.json
packages/flow-core-config/vite.config.js
packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/vite.config.ts
packages/flow-dashboard/CHANGELOG.md
packages/flow-dashboard/package.json
packages/flow-dashboard/vite.config.ts
packages/flow-form-builder/CHANGELOG.md
packages/flow-form-builder/package.json
packages/flow-form-builder/vite.config.ts
packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-icons/vite.config.ts
packages/flow-lineage/CHANGELOG.md
packages/flow-lineage/package.json
packages/flow-lineage/vite.config.ts
packages/flow-log/CHANGELOG.md
packages/flow-log/package.json
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json
packages/flow-table/CHANGELOG.md
packages/flow-table/package.json
packages/flow-table/vite.config.ts
packages/flow-text-editor/CHANGELOG.md
packages/flow-text-editor/package.json
packages/flow-text-editor/vite.config.ts

ssr Make flow packages ES only

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover.ts

- prepending overlay instead of append for f-popover

NFX-459 overlay issue fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover-global.scss
packages/flow-core/src/components/f-popover/f-popover.test.ts
packages/flow-core/src/components/f-popover/f-popover.ts
packages/flow-form-builder/src/components/f-form-builder/f-form-builder.test.ts

- overlay element converted to pseudo element

NFX-459-2 popver overlay converted to pseudo element

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover.ts

- overlay-click event behavior updated

NFX-459 overlay-click event updated

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover.ts
stories/flow-core/f-popover.stories.ts

- overlay-click event behavior updated

popover-fix popover open issue

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover-global.scss
packages/flow-core/src/components/f-popover/f-popover.ts

- overlay-click event behavior updated

popover-bug popover bug resolved

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover-global.scss

popover-z-index popover z-index fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-popover/f-popover-global.scss

tooltip-flickering tooltip flickering issue fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-div/f-div-global.scss
packages/flow-core/src/components/f-div/f-div.ts
packages/flow-core/src/components/f-icon/f-icon.ts
packages/flow-core/src/components/f-select/f-select.scss
packages/flow-core/src/components/f-select/f-select.test.ts
packages/flow-core/src/components/f-select/f-select.ts
packages/flow-core/src/components/f-select/render.ts
packages/flow-core/src/components/f-tag/f-tag.ts
packages/flow-core/src/components/f-text/f-text.ts
packages/flow-core/src/mixins/components/f-root/f-root.ts
packages/flow-core/src/utils/index.ts
stories/flow-core/f-div.stories.ts
stories/flow-core/performance-testing.stories.ts

- All ARIA attributes must now be provided by the consumer, rather than being automatically added by the component itself.
- `f-div`: The `highlight` attribute has been removed due to performance concerns and infrequent use by consumers.
- `f-icon`: The `isValidHttpUrl` method has been removed. We now accept a `url` flag. Set it to `true` when the source is a URL.
- `f-tag`: The dynamic tooltip logic has been removed as it caused performance issues.
- `f-text`: The `highlight` and `editable` attributes have been removed, making `f-text` more lightweight with reduced JavaScript overhead.
- `f-root`: The `mouseHover` flag has been removed as it was used in very specific use cases.
- `f-div`: The `applyBorder` and `applyPadding` JavaScript functions have been converted to CSS for better …

NFX-493 Optimise f-div f-text f-select

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-div/f-div-global.scss
packages/flow-core/src/components/f-div/f-div.ts
packages/flow-core/src/components/f-select/f-select.scss
packages/flow-core/src/components/f-select/render.ts
stories/flow-core/performance-testing.stories.ts

- f-div `variant="round"` fixed
- f-select selected option ellipsis fixed

NFX-493 f-div round variant fixed

---

packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-icons/src/index.ts

icon-pack-fix Export icon packs when registering them and load them in parallel

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-progress-bar/f-progress-bar.scss
packages/flow-core/src/components/f-progress-bar/f-progress-bar.ts
stories/flow-core/f-progress-bar.stories.ts

- `f-progress-bar` animation added

NFX-572 progress bar animation added

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-progress-bar/f-progress-bar.scss

- `f-progress-bar` transition when value changes

NFX-580 progress-bar transition added when value changes

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-counter/f-counter.scss

- `f-icon-button` counter position updated

NFX-650 counter position updated in f-icon-button

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-input/f-input-light-global.scss
packages/flow-core/src/components/f-select/f-select.scss
packages/flow-core/src/components/f-text-area/f-text-area.scss
packages/flow-core/src/components/f-text-area/f-text-area.ts

- `f-select` , 'f-input' ,`f-text-area` transprent category updated

transparent-input transprent input updated

---

packages/flow-icons/package.json
packages/flow-icons/src/index.ts
packages/flow-icons/tsconfig.json
packages/flow-table/CHANGELOG.md
packages/flow-table/package.json
packages/flow-table/src/components/f-table-schema/f-table-schema.ts

Table search bar undefined bug fixed

---

packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/components/f-button/f-button.ts

- `f-button` option click bug fixed.

f-button options click bug fixed

---

.github/workflows/publish-icons.yml
packages/flow-icons/package.json

Icon workflow added

---

.github/workflows/build.yml
.github/workflows/release.yml
pnpm-lock.yaml

Git Actions updated

---

bun.lock
packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-dashboard/CHANGELOG.md
packages/flow-dashboard/package.json
packages/flow-form-builder/CHANGELOG.md
packages/flow-form-builder/package.json
packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

new-theme update stance theme and bump version

---

bun.lock
packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/mixins/scss/_color-tokens.scss
packages/flow-dashboard/CHANGELOG.md
packages/flow-dashboard/package.json
packages/flow-form-builder/CHANGELOG.md
packages/flow-form-builder/package.json
packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

stance-theme-fix-2 Fixed light them base color

---

bun.lock
packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/mixins/scss/_color-tokens.scss
packages/flow-core/src/mixins/scss/_text-tokens.scss
packages/flow-dashboard/CHANGELOG.md
packages/flow-dashboard/package.json
packages/flow-form-builder/CHANGELOG.md
packages/flow-form-builder/package.json
packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

font-weight DM sans font weights

---

bun.lock
packages/flow-core/CHANGELOG.md
packages/flow-core/package.json
packages/flow-core/src/mixins/scss/_color-tokens.scss
packages/flow-dashboard/CHANGELOG.md
packages/flow-dashboard/package.json
packages/flow-form-builder/CHANGELOG.md
packages/flow-form-builder/package.json
packages/flow-icons/CHANGELOG.md
packages/flow-icons/package.json
packages/flow-md-editor/CHANGELOG.md
packages/flow-md-editor/package.json

Border color updated
